spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path

  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER  # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password:  # H2 ?? ? ??? password ?? (??? ??? ??)
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          kakao:
            client-id: b7f2f677a799001df26efe608fba28f4
            client-secret: ak1eVXgBWt44F6cYwFPHIBF91pqQCNe0
            redirect-uri: http://localhost:5500/public/index.html
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email

          google:
            client-id: 221898714674-m4aacsrc3lah7ac1c4k47jlo8vs43e1f.apps.googleusercontent.com # Google? Client ID ?? (??? ??? ??)
            client-secret: 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 # Google? Client Secret ?? (??? ??? ??)
            scope:
              - email
              - profile
            redirect-uri: http://127.0.0.1:5500/public/index.html
  #???? sql? ??? ??
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
